apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: identity
  labels:
    app.kubernetes.io/part-of: open-identity-governance
    app.kubernetes.io/component: identity-provider
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: identity
  labels:
    app.kubernetes.io/part-of: open-identity-governance
    app.kubernetes.io/component: identity-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        app.kubernetes.io/part-of: open-identity-governance
        app.kubernetes.io/component: identity-provider
    spec:
      containers:
        - name:  keycloak
          image: quay.io/keycloak/keycloak:26.3.3
          imagePullPolicy: IfNotPresent

          args:
            - start-dev

          ports:
            - name: http
              containerPort: 8080

          env:
            - name: KC_DB
              value: postgres

            - name: KC_DB_URL
              value: jdbc:postgresql://keycloak-postgresql:5432/keycloak

            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgresql
                  key: POSTGRES_USER

            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgresql
                  key: POSTGRES_PASSWORD

            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin

            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgresql
                  key: POSTGRES_PASSWORD

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 15



