apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgresql-data
  namespace: identity
  labels:
    app.kubernetes.io/part-of: open-identity-governance
    app.kubernetes.io/component: database
spec:
  accessModes: 
    - ReadWriteOnce

  storageClassName: standard

  resources:
    requests:
      storage: 1Gi