apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgresql
  namespace: identity
  labels:
    app.kubernetes.io/part-of: open-identity-governance
    app.kubernetes.io/component: database
spec:
  selector:
    app: keycloak-postgresql
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgresql
  namespace: identity
  labels:
    app.kubernetes.io/part-of: open-identity-governance
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgresql
  template:
    metadata:
      labels:
        app: keycloak-postgresql
        app.kubernetes.io/part-of: open-identity-governance
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: postgresql
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom: 
                secretKeyRef:
                  name: keycloak-postgresql
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgresql
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgresql
                  key: POSTGRES_PASSWORD

          resources: 
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - keycloak
                - -d
                - keycloak
            initialDelaySeconds: 5
            periodSeconds: 5
          
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - keycloak
                - -d
                - keycloak
            initialDelaySeconds: 15
            periodSeconds: 10

            

