apiVersion: v1
kind: Namespace
metadata:
  name: identity
  labels:
    app.kubernetes.io/part-of: open-identity-governance
    security.open-identity-governance/managed: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: security
  labels:
    app.kubernetes.io/part-of: open-identity-governance
    security.open-identity-governance/managed: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: workloads
  labels:
    app.kubernetes.io/part-of: open-identity-governance
    security.open-identity-governance/managed: "true"
