apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: workloads
  labels:
    app.kubernetes.io/part-of: open-identity-governance
    app.kubernetes.io/component: identity

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analyst
  namespace: workloads
  labels:
    app.kubernetes.io/part-of: open-identity-governance
    app.kubernetes.io/component: identity

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: administrator
  namespace: workloads
  labels:
    app.kubernetes.io/part-of: open-identity-governance
    app.kubernetes.io/component: identity

